config/routes.rb
Rails.application.routes.draw do
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, :only => [:show, :edit, :update, :destroy]


  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to :action => :show, :id => @event
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to :action => :index
  end

  private
  def event_params
    params.require(:event).permit(:name, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say
  end
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

app/views/events/edit.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event } do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
  <li>
 	  <%= event.name %>
    <%= link_to 'Show', :controller => 'events', :action => 'show', :id => event %>
    <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
    <%= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event %>
  </li>
<% end %>
</ul>
<%= link_to 'New Event', :controller => 'events', :action => 'new' %>

app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action =>'create' } do |f|%>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', :controller => 'events', :action => 'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class='main'>
  <div class="container">
    <p>Hola! It is <%= Time.now %> </p>
    <p> <%= link_to 'Hello!', welcome_say_hello_path %></p>
  </div>
</div>

app/views/welcome/say.html.erb
<div class='main'>
  <div class="container">
    <h1> Hello Word! </h1>
    <p><%= link_to "Home", root_path %></p>
  </div>
</div>